### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by elpinal** [elpinal/elt0#1]
- [x] Subtyping: especially for practical environment matching
  - [x] Width subtyping for register files
- [x] Polymorphism
  - [x] Stack polymorphism
- [ ] Array support
  - It needs consideration of bounds check
- [ ] Module system
  - To implement a module language suitable for the current core language requires to read some papers (this list is in an arbitrary order):
    - [x] Neal Glew and Greg Morrisett. _Type-Safe Linking and Modular Assembly Language_.  In the Twenty-Sixth ACM SIGPLAN-SIGACT Symposium on Principles of Programming Languages, pages 250-261, San Antonio, TX, USA, January 1999.
    - [x] David MacQueen. _Using dependent types to express modular structure_. In 13th ACM Symp. on Principles of Prog. Lang., 1986.
    - [x] Robert Harper and Mark Lillibridge. _A type-theoretic approach to higher-order modules with sharing_. In 21st ACM Symp. Principles of Prog. Lang., 1994.
    - [x] Xavier Leroy. _Manifest types, modules, and separate compilation_. In Proc. 21st Symp. Principles of Prog. Lang., pages 109–122. ACM Press, 1994.
    - [x] Xavier Leroy. _Applicative functors and fully transparent higher-order modules_. In Proc. 22nd Symp. Principles of Prog. Lang., pages 142–153. ACM Press, 1995.
    - [ ] Xavier Leroy. _A syntactic theory of type generativity and sharing_. In Journal of Functional Programming, 6(5):1—32, September 1996.
    - [x] Robert Harper, John Mitchell, and Eugenio Moggi. _Higher-order modules and the phase distinction_. In Seventeenth ACM SIGPLAN-SIGACT Symposium on Principles of Programming Languages, pages 341–354, January 1990.
    - [x] Derek Dreyer. _A Type System for Recursive Modules_. In 2007 ACM SIGPLAN International Conference on Functional Programming.
    - [x] Davide Ancona, Sonia Fagorzi, Eugenio Moggi, and Elena Zucca. 2003. _Mixin modules and computational effects_. In Proceedings of the 30th international conference on Automata, languages and programming (ICALP'03). Springer-Verlag, Berlin, Heidelberg, 224-238.
    - [ ] Derek Dreyer and Andreas Rossberg. 2008. _Mixin' up the ML module system_. In Proceedings of the 13th ACM SIGPLAN international conference on Functional programming (ICFP '08). ACM, New York, NY, USA, 307-320.
    - [x] Derek Dreyer, Karl Crary, and Robert Harper. _A type system for higher-order modules_. In Thirtieth ACM Symposium on Principles of Programming Languages, pages 236–249, New Orleans, Louisiana, January 2003.
    - [ ] Karl Crary. _Modules, Abstraction, and Parametric Polymorphism_. 2017 Symposium on Principles of Programming Languages.
